export interface AssetScopeConfig {
  id: string;
  name: string;
  scopes: string[];
}

export const ASSESSMENT_ASSETS: AssetScopeConfig[] = [
  {
    id: 'transformers',
    name: '1. Transformers',
    scopes: [
      'Review transformer capacity, loading pattern, operating hours, and efficiency.',
      'Measure voltage, current, kW, kVA, power factor, and loading.',
      'Assess no-load and load losses.',
      'Review transformer utilization and potential for load optimization.',
      'Identify opportunities for transformer loss reduction and capacity optimization.',
    ],
  },
  {
    id: 'bill_analysis',
    name: '2. Energy Bill Analysis',
    scopes: [
      'Review electricity bills for the previous 12–24 months.',
      'Analyze maximum demand, energy consumption, power factor, tariff, TOD consumption, and demand charges.',
      'Analyze monthly consumption trends and specific energy consumption.',
      'Identify billing anomalies and avoidable penalties.',
      'Assess potential benefits from demand management, tariff optimization, and load shifting.',
    ],
  },
  {
    id: 'motors',
    name: '3. Motors',
    scopes: [
      'Prepare an inventory of major motors.',
      'Review motor rating, loading, operating hours, efficiency, and control method.',
      'Measure electrical parameters and operating load.',
      'Assess oversized/underloaded motors.',
      'Evaluate opportunities for high-efficiency motor replacement and VFD installation.',
    ],
  },
  {
    id: 'pumps',
    name: '4. Pumps / Water Pumping System',
    scopes: [
      'Assess pump capacity, flow, head, pressure, and power consumption.',
      'Measure pump operating parameters.',
      'Calculate pump efficiency and specific energy consumption.',
      'Review throttling, bypass operation, and control methods.',
      'Evaluate VFD and pump optimization opportunities.',
    ],
  },
  {
    id: 'compressors',
    name: '5. Compressors / Compressed Air System',
    scopes: [
      'Assess compressor capacity, loading/unloading pattern, pressure, and operating hours.',
      'Measure compressor power and compressed-air flow.',
      'Determine specific power consumption in kW/CFM or kW/m³/min.',
      'Conduct compressed-air leakage assessment.',
      'Review compressor sequencing and pressure settings.',
      'Evaluate receiver capacity, pressure drop, and air distribution.',
      'Identify opportunities for pressure optimization, leak reduction, VFD compressors, and heat recovery.',
    ],
  },
  {
    id: 'air_chillers',
    name: '6. Air-Cooled Chillers',
    scopes: [
      'Assess chiller operating efficiency in kW/TR.',
      'Measure chilled-water supply/return temperatures and flow.',
      'Record compressor power, ambient temperature, and cooling load.',
      'Assess condenser condition and airflow.',
      'Review part-load performance and operating sequence.',
      'Identify opportunities for set-point optimization, condenser maintenance, and chiller sequencing.',
    ],
  },
  {
    id: 'water_chillers',
    name: '7. Water-Cooled Chillers',
    scopes: [
      'Measure chilled-water and condenser-water temperatures and flow.',
      'Determine cooling capacity and chiller efficiency.',
      'Calculate kW/TR at different loading conditions.',
      'Assess chilled-water ΔT and condenser-water ΔT.',
      'Review chiller loading, sequencing, and operating strategy.',
      'Assess cooling tower and condenser-water system performance.',
      'Identify opportunities for optimization of chillers, pumps, and controls.',
    ],
  },
  {
    id: 'cooling_towers',
    name: '8. Cooling Towers',
    scopes: [
      'Assess cooling tower approach temperature and range.',
      'Measure water flow, fan power, and operating conditions.',
      'Review fan control and VFD operation.',
      'Assess condenser-water temperature reset opportunities.',
      'Evaluate fan operation, fill condition, water distribution, and maintenance.',
      'Identify opportunities for optimized cooling tower operation.',
    ],
  },
  {
    id: 'ahus',
    name: '9. AHUs',
    scopes: [
      'Assess AHU airflow, temperature, humidity, static pressure, and power consumption.',
      'Review supply-air and return-air conditions.',
      'Assess fresh-air quantity and ventilation requirements.',
      'Review filter pressure drop and coil condition.',
      'Evaluate fan operation and VFD control.',
      'Identify opportunities for airflow optimization and temperature/set-point optimization.',
    ],
  },
  {
    id: 'fans',
    name: '10. Fresh-Air / Exhaust Fans',
    scopes: [
      'Assess fan capacity, airflow, static pressure, and power consumption.',
      'Review operating hours and control philosophy.',
      'Assess whether fans are oversized or continuously operated.',
      'Evaluate VFD/control-based energy-saving opportunities.',
      'Identify opportunities for demand-based ventilation and optimized operating schedules.',
    ],
  },
  {
    id: 'elec_boilers',
    name: '11. Electrical Boilers',
    scopes: [
      'Assess electrical input, thermal output, operating hours, and efficiency.',
      'Review boiler loading and temperature/pressure settings.',
      'Assess heat losses and insulation condition.',
      'Evaluate operating schedule and load optimization.',
      'Identify opportunities for improved controls and thermal efficiency.',
    ],
  },
  {
    id: 'boilers',
    name: '12. Boilers',
    scopes: [
      'Assess boiler efficiency through input-output analysis.',
      'Review fuel consumption, steam generation, pressure, temperature, and operating hours.',
      'Conduct combustion analysis, where applicable.',
      'Assess excess air, flue-gas temperature, and combustion efficiency.',
      'Review blowdown losses and condensate recovery.',
      'Assess insulation and steam distribution losses.',
      'Identify opportunities for fuel and thermal energy savings.',
    ],
  },
  {
    id: 'steam_system',
    name: '13. Steam System',
    scopes: [
      'Assess steam generation, distribution, and utilization.',
      'Review steam pressure and temperature.',
      'Inspect steam traps and identify failed/open traps.',
      'Assess condensate recovery.',
      'Review steam leakage and insulation condition.',
      'Evaluate flash steam recovery opportunities.',
      'Identify pressure optimization and heat recovery opportunities.',
    ],
  },
  {
    id: 'heat_exchangers',
    name: '14. Heat Exchangers',
    scopes: [
      'Assess heat exchanger inlet/outlet temperatures and flow rates.',
      'Calculate heat-transfer capacity and effectiveness.',
      'Review approach temperature and pressure drop.',
      'Assess fouling and maintenance condition.',
      'Identify opportunities for improved heat recovery and process integration.',
    ],
  },
  {
    id: 'elec_ovens',
    name: '15. Oven / Electrical Oven',
    scopes: [
      'Assess oven temperature profile, energy consumption, operating hours, and production throughput.',
      'Review heating system efficiency and circulation airflow.',
      'Assess insulation and heat losses.',
      'Review fresh-air/exhaust-air quantity.',
      'Evaluate temperature set-point optimization.',
      'Determine specific energy consumption per unit of production.',
    ],
  },
  {
    id: 'furnaces',
    name: '16. Furnace / Electrical Furnace',
    scopes: [
      'Assess fuel/electrical energy consumption and production output.',
      'Review temperature profile and operating cycle.',
      'Assess combustion efficiency, where applicable.',
      'Evaluate insulation and heat losses.',
      'Review loading pattern and operating schedule.',
      'Identify heat recovery and process optimization opportunities.',
    ],
  },
  {
    id: 'heat_pumps',
    name: '17. Heat Pumps',
    scopes: [
      'Measure electrical input and thermal output.',
      'Calculate COP under different operating conditions.',
      'Assess source-side and load-side temperatures and flow.',
      'Review compressor and pump operation.',
      'Identify opportunities for temperature optimization and operating schedule improvement.',
    ],
  },
  {
    id: 'hw_generators',
    name: '18. Hot Water Generators',
    scopes: [
      'Assess fuel/electricity consumption and hot-water generation.',
      'Measure inlet/outlet water temperatures and flow.',
      'Calculate thermal efficiency.',
      'Review operating temperature and circulation system.',
      'Assess insulation and distribution losses.',
      'Identify heat recovery and set-point optimization opportunities.',
    ],
  },
  {
    id: 'refrigeration',
    name: '19. Refrigeration Systems',
    scopes: [
      'Assess refrigeration compressor power and operating conditions.',
      'Measure suction/discharge pressure and temperature.',
      'Assess evaporator and condenser performance.',
      'Review refrigerant operating conditions.',
      'Calculate COP/EER where sufficient data is available.',
      'Identify opportunities for temperature optimization, condenser improvement, and compressor sequencing.',
    ],
  },
  {
    id: 'dg_sets',
    name: '20. DG Sets',
    scopes: [
      'Review DG capacity, operating hours, fuel consumption, and loading.',
      'Conduct fuel consumption versus load analysis.',
      'Calculate specific fuel consumption.',
      'Assess electrical loading and power factor.',
      'Review DG operating practices and synchronization.',
      'Identify opportunities for improved loading and fuel efficiency.',
    ],
  },
  {
    id: 'lighting',
    name: '21. Lighting System',
    scopes: [
      'Prepare lighting inventory.',
      'Measure illumination levels at representative locations.',
      'Assess installed lighting load and operating hours.',
      'Review LED conversion opportunities.',
      'Evaluate occupancy/daylight-based controls.',
      'Identify over-illumination and unnecessary operating hours.',
    ],
  },
  {
    id: 'vrv_vrf',
    name: '22. VRV / VRF Systems',
    scopes: [
      'Assess outdoor and indoor unit performance.',
      'Measure electrical consumption and operating conditions.',
      'Review set points, operating schedules, and loading.',
      'Assess refrigerant system performance.',
      'Review zoning and simultaneous heating/cooling conditions.',
      'Identify control and set-point optimization opportunities.',
    ],
  },
  {
    id: 'split_ac',
    name: '23. Split AC',
    scopes: [
      'Assess AC capacity, electrical consumption, operating hours, and set points.',
      'Measure indoor/outdoor temperatures.',
      'Review filter, coil, condenser, and refrigerant condition.',
      'Assess temperature set-point optimization.',
      'Identify opportunities for maintenance, scheduling, and high-efficiency equipment replacement.',
    ],
  },
  {
    id: 'blowers',
    name: '24. Blowers',
    scopes: [
      'Assess blower airflow, static pressure, power consumption, and operating hours.',
      'Review damper/throttling losses.',
      'Assess motor loading.',
      'Evaluate VFD implementation and airflow optimization.',
      'Determine specific energy consumption.',
    ],
  },
  {
    id: 'dx_units',
    name: '25. DX Units',
    scopes: [
      'Assess DX unit cooling capacity and electrical consumption.',
      'Measure air temperature, airflow, and operating conditions.',
      'Review compressor loading and control.',
      'Assess filter and coil condition.',
      'Identify opportunities for temperature, airflow, and operating schedule optimization.',
    ],
  },
  {
    id: 'elevators',
    name: '26. Elevators / Lifts',
    scopes: [
      'Review lift capacity, operating hours, traffic pattern, and energy consumption.',
      'Assess motor and drive technology.',
      'Review standby/sleep mode operation.',
      'Evaluate regenerative drive opportunities, where technically feasible.',
      'Identify opportunities for optimized operation and energy-efficient controls.',
    ],
  },
  {
    id: 'solar_pv',
    name: '27. Solar PV System',
    scopes: [
      'Review installed PV capacity and generation data.',
      'Assess solar generation versus expected generation.',
      'Analyze inverter performance and performance ratio.',
      'Review module cleanliness, shading, and system availability.',
      'Identify performance gaps and maintenance opportunities.',
      'Assess potential for increasing renewable-energy utilization.',
    ],
  },
  {
    id: 'power_factor',
    name: '28. Power Factor Correction',
    scopes: [
      'Review power factor at incomer and major loads.',
      'Assess capacitor bank operation and sizing.',
      'Review harmonic levels where applicable.',
      'Assess capacitor switching and APFC performance.',
      'Identify opportunities to reduce maximum demand and reactive-power charges.',
    ],
  },
  {
    id: 'building_envelope',
    name: '29. Building Envelope',
    scopes: [
      'Assess walls, roofs, windows, doors, glazing, and insulation.',
      'Identify major sources of heat gain/loss.',
      'Conduct thermal imaging/thermography where applicable.',
      'Assess infiltration and air leakage.',
      'Evaluate insulation, shading, glazing, and reflective-surface opportunities.',
      'Quantify potential HVAC energy savings.',
    ],
  },
  {
    id: 'benchmarking',
    name: '30. Benchmarking',
    scopes: [
      'Benchmark energy performance against industry standards, similar facilities, historical performance, and internal benchmarks.',
      'Develop appropriate Energy Performance Indicators (EnPIs).',
      'Identify significant energy-use areas and performance gaps.',
    ],
  },
  {
    id: 'process_equipment',
    name: '31. Process Equipment',
    scopes: [
      'Identify major energy-consuming process equipment.',
      'Assess electrical and thermal energy consumption.',
      'Correlate energy consumption with production output.',
      'Determine specific energy consumption.',
      'Review operating practices, loading, idling, and process parameters.',
      'Identify process optimization and energy-saving opportunities.',
    ],
  },
  {
    id: 'air_balancing',
    name: '32. Air Balancing',
    scopes: [
      'Pre-Balancing Inspection – Inspect AHU/FCU, ducting, dampers, diffusers and grilles to verify the existing system condition.',
      'Airflow Measurement – Measure supply, return, fresh-air and exhaust-air quantities at respective terminals using calibrated instruments.',
      'Airflow Balancing – Adjust VCDs, balancing dampers and terminal dampers to achieve the required/design airflow for each room or zone.',
      'Final Verification – Re-measure the airflow after adjustment and verify the system is operating within the agreed design tolerance.',
      'Air Balancing Report – Submit a report containing design vs. actual airflow, pressure/temperature readings, adjustments carried out, observations and recommendations.',
    ],
  },
];
